"""Charity Dashboard — per-category roll-up with prior-year comparison.

A read-only SQL view that aggregates validated timesheet hours,
validated charity-tagged attendance, and confirmed contributions into
ONE row per ``(lodge_year, charity_category)`` pair.  The dashboard
kanban view uses these rows to render widget cards for every Grand
Lodge category, sorted by code (1001 → 9999), with the prior lodge
year's totals computed alongside for year-over-year comparison.

The view is intentionally generated by cross-joining every category
with every lodge year so that categories with **zero** activity still
appear (so the lodge sees what they haven't done yet and is motivated
to act).  Rows are filtered to a specific lodge year at view time via
the default search filter.

Dedup rule (mirrored from project.task._compute_totals): if both a
validated timesheet line and a validated attendance record exist for
the same ``(employee_id, date, task_id)``, the attendance row wins
and the timesheet duplicate is excluded from the totals.
"""
import datetime

from odoo import api, fields, models, tools
from odoo.tools.safe_eval import safe_eval


def _current_lodge_year():
    """Return the current lodge year string, e.g. '2026-2027'.

    Lodge year runs April 1 → March 31.
    """
    today = datetime.date.today()
    if today.month >= 4:
        return f"{today.year}-{today.year + 1}"
    return f"{today.year - 1}-{today.year}"


class ElksCharityDashboard(models.Model):
    _name = "elks.charity.dashboard"
    _description = "Charity Dashboard (Per Category)"
    _auto = False  # backed by a SQL VIEW
    _order = "category_code, lodge_year"
    _rec_name = "category_id"

    # ── identity ────────────────────────────────────────────────
    category_id = fields.Many2one(
        "elks.charity.category", string="Charity Category", readonly=True,
    )
    category_code = fields.Char("GL Code", readonly=True, index=True)
    category_name = fields.Char("Category", readonly=True)
    gl_section = fields.Selection(
        selection=lambda self: self.env["elks.charity.category"]._fields[
            "gl_section"
        ].selection,
        string="GL Section", readonly=True,
    )
    lodge_year = fields.Char("Lodge Year", readonly=True, index=True)

    # ── current-period roll-ups (from the SQL view) ─────────────
    elks_hours = fields.Float("Elks Hours", readonly=True)
    helper_hours = fields.Float("Helper Hours", readonly=True)
    total_hours = fields.Float("Total Hours", readonly=True)
    elks_unique = fields.Integer("# Unique Elks", readonly=True)
    helper_unique = fields.Integer("# Unique Helpers", readonly=True)
    elks_headcount = fields.Integer("Elks Head Count", readonly=True)
    helper_headcount = fields.Integer("Helper Head Count", readonly=True)
    elks_miles = fields.Float("Elks Miles", readonly=True)
    helper_miles = fields.Float("Helper Miles", readonly=True)
    cash_raised = fields.Monetary(
        "$ Raised", currency_field="currency_id", readonly=True,
    )
    non_cash_raised = fields.Monetary(
        "Non-$ Value", currency_field="currency_id", readonly=True,
    )
    activity_count = fields.Integer("# Activities", readonly=True)
    currency_id = fields.Many2one(
        "res.currency", readonly=True,
        default=lambda self: self.env.company.currency_id,
    )

    # ── prior-year roll-ups (Python-computed, not stored) ───────
    prior_lodge_year = fields.Char(
        "Prior Lodge Year", compute="_compute_prior_year",
    )
    prior_elks_hours = fields.Float(
        "Prior Elks Hours", compute="_compute_prior_year",
    )
    prior_helper_hours = fields.Float(
        "Prior Helper Hours", compute="_compute_prior_year",
    )
    prior_total_hours = fields.Float(
        "Prior Total Hours", compute="_compute_prior_year",
    )
    prior_elks_unique = fields.Integer(
        "Prior # Unique Elks", compute="_compute_prior_year",
    )
    prior_helper_unique = fields.Integer(
        "Prior # Unique Helpers", compute="_compute_prior_year",
    )
    prior_elks_headcount = fields.Integer(
        "Prior Elks Head Count", compute="_compute_prior_year",
    )
    prior_helper_headcount = fields.Integer(
        "Prior Helper Head Count", compute="_compute_prior_year",
    )
    prior_cash_raised = fields.Monetary(
        "Prior $ Raised", currency_field="currency_id",
        compute="_compute_prior_year",
    )
    prior_non_cash_raised = fields.Monetary(
        "Prior Non-$ Value", currency_field="currency_id",
        compute="_compute_prior_year",
    )

    # ── deltas (current − prior) for nice arrows in the kanban ──
    delta_total_hours = fields.Float(
        "Δ Total Hours", compute="_compute_deltas",
    )
    delta_elks_unique = fields.Integer(
        "Δ Unique Elks", compute="_compute_deltas",
    )
    delta_helper_unique = fields.Integer(
        "Δ Unique Helpers", compute="_compute_deltas",
    )
    delta_cash_raised = fields.Monetary(
        "Δ $ Raised", currency_field="currency_id",
        compute="_compute_deltas",
    )
    delta_non_cash_raised = fields.Monetary(
        "Δ Non-$ Value", currency_field="currency_id",
        compute="_compute_deltas",
    )
    trend_total_hours = fields.Selection(
        [("up", "Up"), ("flat", "Flat"), ("down", "Down")],
        compute="_compute_deltas", string="Hours Trend",
        search="_search_trend_total_hours",
    )
    trend_cash_raised = fields.Selection(
        [("up", "Up"), ("flat", "Flat"), ("down", "Down")],
        compute="_compute_deltas", string="$ Trend",
        search="_search_trend_cash_raised",
    )

    # ------------------------------------------------------------------
    # Searchable wrappers for the computed trend fields
    # ------------------------------------------------------------------
    def _trend_search(self, field_name, operator, value):
        """Common search implementation for trend_* selection fields.

        Loads all dashboard rows (small set — ~31 categories × N lodge
        years), recomputes the trend in Python, and returns an id-domain.
        """
        if operator not in ("=", "!=", "in", "not in"):
            # Unknown operator: accept all rather than crash.
            return [(1, "=", 1)]
        if isinstance(value, str) or value is False or value is None:
            targets = {value} if value else set()
        else:
            targets = set(value or [])
        records = self.with_context(active_test=False).search([])
        matching = records.filtered(lambda r: r[field_name] in targets)
        if operator in ("=", "in"):
            return [("id", "in", matching.ids or [0])]
        return [("id", "not in", matching.ids or [0])]

    def _search_trend_total_hours(self, operator, value):
        return self._trend_search("trend_total_hours", operator, value)

    def _search_trend_cash_raised(self, operator, value):
        return self._trend_search("trend_cash_raised", operator, value)

    # ------------------------------------------------------------------
    # Prior-year lookups
    # ------------------------------------------------------------------
    @staticmethod
    def _prior_lodge_year_str(lodge_year):
        """Given '2026-2027' return '2025-2026' (or None if unparseable)."""
        if not lodge_year or "-" not in lodge_year:
            return None
        try:
            start, end = lodge_year.split("-")
            return f"{int(start) - 1}-{int(end) - 1}"
        except (TypeError, ValueError):
            return None

    @api.depends("lodge_year", "category_id")
    def _compute_prior_year(self):
        """Look up the prior lodge year's row for the same category."""
        # Batch: collect every (category, prior_year) we need, then query once.
        needed = {}
        for rec in self:
            rec.prior_lodge_year = self._prior_lodge_year_str(rec.lodge_year)
            if rec.prior_lodge_year and rec.category_id:
                key = (rec.category_id.id, rec.prior_lodge_year)
                needed.setdefault(key, self.env[self._name])

        if needed:
            cat_ids = list({k[0] for k in needed})
            years = list({k[1] for k in needed})
            prior_rows = self.search([
                ("category_id", "in", cat_ids),
                ("lodge_year", "in", years),
            ])
            for prior in prior_rows:
                key = (prior.category_id.id, prior.lodge_year)
                if key in needed:
                    needed[key] = prior

        for rec in self:
            key = (rec.category_id.id if rec.category_id else 0,
                   rec.prior_lodge_year)
            prior = needed.get(key) if key[1] else None
            if prior:
                rec.prior_elks_hours = prior.elks_hours
                rec.prior_helper_hours = prior.helper_hours
                rec.prior_total_hours = prior.total_hours
                rec.prior_elks_unique = prior.elks_unique
                rec.prior_helper_unique = prior.helper_unique
                rec.prior_elks_headcount = prior.elks_headcount
                rec.prior_helper_headcount = prior.helper_headcount
                rec.prior_cash_raised = prior.cash_raised
                rec.prior_non_cash_raised = prior.non_cash_raised
            else:
                rec.prior_elks_hours = 0.0
                rec.prior_helper_hours = 0.0
                rec.prior_total_hours = 0.0
                rec.prior_elks_unique = 0
                rec.prior_helper_unique = 0
                rec.prior_elks_headcount = 0
                rec.prior_helper_headcount = 0
                rec.prior_cash_raised = 0.0
                rec.prior_non_cash_raised = 0.0

    @api.depends(
        "total_hours", "prior_total_hours",
        "elks_unique", "prior_elks_unique",
        "helper_unique", "prior_helper_unique",
        "cash_raised", "prior_cash_raised",
        "non_cash_raised", "prior_non_cash_raised",
    )
    def _compute_deltas(self):
        for rec in self:
            rec.delta_total_hours = rec.total_hours - rec.prior_total_hours
            rec.delta_elks_unique = rec.elks_unique - rec.prior_elks_unique
            rec.delta_helper_unique = (
                rec.helper_unique - rec.prior_helper_unique
            )
            rec.delta_cash_raised = rec.cash_raised - rec.prior_cash_raised
            rec.delta_non_cash_raised = (
                rec.non_cash_raised - rec.prior_non_cash_raised
            )
            rec.trend_total_hours = (
                "up" if rec.delta_total_hours > 0.01
                else "down" if rec.delta_total_hours < -0.01
                else "flat"
            )
            rec.trend_cash_raised = (
                "up" if rec.delta_cash_raised > 0.01
                else "down" if rec.delta_cash_raised < -0.01
                else "flat"
            )

    # ------------------------------------------------------------------
    # Website snippet — sudo-safe aggregates only.
    # No individual contributor names, no per-employee records.  Pure
    # category-level rollups so the snippet can render on a fully
    # public page without leaking personal data.
    # ------------------------------------------------------------------
    @api.model
    def _website_totals(self, lodge_year=None):
        """Aggregated charity impact totals for the public website.

        Returns a dict with:
            current_year, prior_year                    — lodge year strings
            totals.{hours,cash,non_cash,people_served}  — current year sums
            prior.{...}                                 — same for prior year
            deltas.{...}                                — current - prior
            pct.{...}                                   — % change (or None)
            cards                                       — list of per-category
                                                          dicts sorted by code
        Safe to call without an authenticated user; the caller should
        sudo() before invoking on the public website.
        """
        lodge_year = lodge_year or _current_lodge_year()
        prior_year = self._prior_lodge_year_str(lodge_year)

        def _aggs(year):
            if not year:
                return {
                    'hours': 0.0, 'cash': 0.0, 'non_cash': 0.0,
                    'people_served': 0,
                }
            rows = self.search([('lodge_year', '=', year)])
            return {
                'hours': sum(rows.mapped('total_hours')),
                'cash': sum(rows.mapped('cash_raised')),
                'non_cash': sum(rows.mapped('non_cash_raised')),
                'people_served': sum(rows.mapped('elks_headcount'))
                                 + sum(rows.mapped('helper_headcount')),
            }

        totals = _aggs(lodge_year)
        prior = _aggs(prior_year)

        def _delta_pct(cur, old):
            if not old:
                return None
            return round(((cur - old) / old) * 100.0, 1)

        deltas = {k: totals[k] - prior[k] for k in totals}
        pct = {k: _delta_pct(totals[k], prior[k]) for k in totals}

        # Per-category cards — sorted by GL code asc.
        cards = []
        for row in self.search([('lodge_year', '=', lodge_year)],
                               order='category_code'):
            prior_row = self.search([
                ('lodge_year', '=', prior_year),
                ('category_id', '=', row.category_id.id),
            ], limit=1) if prior_year else None
            prior_hours = prior_row.total_hours if prior_row else 0.0
            prior_cash = prior_row.cash_raised if prior_row else 0.0
            cards.append({
                'code': row.category_code,
                'name': row.category_name,
                'section': row.category_id.gl_section
                          and dict(row.category_id._fields['gl_section'].selection)
                              .get(row.category_id.gl_section, ''),
                'hours': row.total_hours,
                'cash': row.cash_raised,
                'non_cash': row.non_cash_raised,
                'people_served': row.elks_headcount + row.helper_headcount,
                'activity_count': row.activity_count,
                'prior_hours': prior_hours,
                'prior_cash': prior_cash,
                'delta_hours': row.total_hours - prior_hours,
                'delta_cash': row.cash_raised - prior_cash,
            })

        return {
            'current_year': lodge_year,
            'prior_year': prior_year,
            'totals': totals,
            'prior': prior,
            'deltas': deltas,
            'pct': pct,
            'cards': cards,
            'currency': self.env.company.currency_id,
        }

    # ------------------------------------------------------------------
    # Open dashboard (entry point used by the root menu)
    # ------------------------------------------------------------------
    @api.model
    def action_open_dashboard(self):
        """Return the dashboard act_window pre-filtered to the current
        lodge year via the search field.  Used as the default landing
        for the Elks Charity app.
        """
        action = self.env["ir.actions.act_window"]._for_xml_id(
            "elkscharity.action_charity_dashboard"
        )
        # ir.actions.act_window stores `context` as a Python-source
        # string (e.g. "{'default_x': 1}"). Eval it to a dict before
        # merging — passing a string directly to dict() raises
        # "dictionary update sequence element ... length 1; 2 required".
        raw_ctx = action.get("context") or {}
        if isinstance(raw_ctx, str):
            try:
                base_ctx = safe_eval(raw_ctx) or {}
            except Exception:
                base_ctx = {}
        else:
            base_ctx = dict(raw_ctx)
        base_ctx.update(
            current_lodge_year=_current_lodge_year(),
            # Activate the "Current Lodge Year" named filter so only
            # this year's cards show by default.  User can clear it
            # from the search bar to see all years.
            search_default_filter_current_lodge_year=1,
        )
        action["context"] = base_ctx
        return action

    # ------------------------------------------------------------------
    # Drill-down
    # ------------------------------------------------------------------
    def action_open_category_activities(self):
        """Open the project.task list filtered by this category + lodge year."""
        self.ensure_one()
        list_view = self.env.ref(
            "elkscharity.view_task_tree_charity_activities", raise_if_not_found=False
        )
        views = []
        if list_view:
            views.append((list_view.id, "list"))
        else:
            views.append((False, "list"))
        views += [(False, "pivot"), (False, "graph"), (False, "form")]
        domain = [
            ("x_is_charity_activity", "=", True),
            ("x_charity_category_id", "=", self.category_id.id),
        ]
        if self.lodge_year:
            domain.append(("x_lodge_year", "=", self.lodge_year))
        return {
            "type": "ir.actions.act_window",
            "name": f"{self.category_code} — {self.category_name}",
            "res_model": "project.task",
            "view_mode": "list,pivot,graph,form",
            "views": views,
            "domain": domain,
            "context": {
                "default_x_charity_category_id": self.category_id.id,
                "search_default_group_lodge_year": 1,
            },
        }

    def action_open_category_hours(self):
        """Open the unified hours report filtered to this category + lodge year."""
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": f"Hours: {self.category_code} {self.category_name}",
            "res_model": "elks.charity.hours.report",
            "view_mode": "list,pivot,graph",
            "domain": [
                ("charity_category_id", "=", self.category_id.id),
                ("lodge_year", "=", self.lodge_year),
            ],
        }

    def action_quick_entry(self):
        """Launch the Quick Entry wizard pre-filled with this card's
        charity category."""
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": f"Quick Entry — {self.category_code} {self.category_name}",
            "res_model": "elks.charity.quick.entry.wizard",
            "view_mode": "form",
            "target": "new",
            "context": {
                "default_charity_category_id": self.category_id.id,
            },
        }

    # ------------------------------------------------------------------
    # SQL view
    # ------------------------------------------------------------------
    def init(self):
        """Build the SQL view.

        Strategy:

        1. ``deduped_lines`` — UNION ALL of:
              a) validated attendance rows tagged with a charity task
              b) validated timesheet lines on charity tasks that do NOT
                 have a same-(employee, date, task) attendance row
                 (attendance wins the duplicate).

        2. ``contribs`` — confirmed elks.charity.contribution rows
           (additive — no duplicate-with-attendance issue).

        3. ``activity`` — aggregate counts of activity tasks per
           (category, lodge_year).

        4. ``base`` — every (category, lodge_year) combination where at
           least one project task exists in a charity-parent project for
           that year.  We DON'T cross-join all categories — the lodge
           only wants cards for charities they've actually taken on, not
           empty placeholders for every GL code 1001-9999.

        5. The outer SELECT joins base ⟕ aggregated rows.
        """
        tools.drop_view_if_exists(self.env.cr, self._table)
        query = """
            CREATE OR REPLACE VIEW {table} AS (
                WITH base AS (
                    -- Only (category, lodge_year) combinations where at
                    -- least one project task exists in a charity-parent
                    -- project for that lodge year.  This avoids
                    -- cluttering the dashboard with empty cards for
                    -- GL codes the lodge hasn't taken on.
                    SELECT DISTINCT
                        cat.id            AS category_id,
                        cat.code          AS category_code,
                        cat.name          AS category_name,
                        cat.gl_section    AS gl_section,
                        pp.x_lodge_year   AS lodge_year
                    FROM elks_charity_category cat
                    JOIN project_task pt
                          ON pt.x_charity_category_id = cat.id
                    JOIN project_project pp
                          ON pp.id = pt.project_id
                    WHERE pp.x_is_charity_parent = TRUE
                      AND pp.x_lodge_year IS NOT NULL
                      AND cat.active = TRUE
                ),
                deduped_lines AS (
                    -- (a) Validated charity-tagged attendance rows.
                    --     Hours = explicit x_charity_hours when set,
                    --     otherwise the raw clock-in → clock-out
                    --     duration (NOT worked_hours, which subtracts
                    --     resource-calendar lunch breaks).
                    SELECT
                        pt.x_charity_category_id   AS category_id,
                        pp.x_lodge_year            AS lodge_year,
                        ha.employee_id             AS employee_id,
                        CASE
                            WHEN COALESCE(ha.x_charity_hours, 0) > 0
                                THEN ha.x_charity_hours
                            WHEN ha.check_in IS NOT NULL
                                 AND ha.check_out IS NOT NULL
                                THEN EXTRACT(EPOCH FROM
                                        (ha.check_out - ha.check_in))
                                     / 3600.0
                            ELSE COALESCE(ha.worked_hours, 0)
                        END                        AS hours,
                        COALESCE(ha.x_is_helper, FALSE)  AS is_helper,
                        COALESCE(ha.x_miles, 0)          AS miles,
                        COALESCE(ha.x_cash_value, 0)     AS cash_value,
                        COALESCE(ha.x_non_cash_value, 0) AS non_cash_value
                    FROM hr_attendance ha
                    JOIN project_task pt
                          ON pt.id = ha.x_charity_task_id
                    JOIN project_project pp
                          ON pp.id = pt.project_id
                    WHERE ha.x_charity_task_id IS NOT NULL
                      AND ha.x_validated = TRUE
                      AND pp.x_is_charity_parent = TRUE
                      AND pt.x_charity_category_id IS NOT NULL

                    UNION ALL

                    -- (b) Validated timesheet lines NOT duplicated by
                    --     attendance, AND NOT personal-record-only.
                    --     Personal-record lines are created by the Quick
                    --     Entry wizard for member personal history; the
                    --     bulk totals live on the contribution row, so
                    --     including these here would double-count.
                    SELECT
                        pt.x_charity_category_id   AS category_id,
                        pp.x_lodge_year            AS lodge_year,
                        aal.employee_id            AS employee_id,
                        aal.unit_amount            AS hours,
                        COALESCE(aal.x_is_helper, FALSE)  AS is_helper,
                        COALESCE(aal.x_miles, 0)          AS miles,
                        COALESCE(aal.x_cash_value, 0)     AS cash_value,
                        COALESCE(aal.x_non_cash_value, 0) AS non_cash_value
                    FROM account_analytic_line aal
                    JOIN project_task pt
                          ON pt.id = aal.task_id
                    JOIN project_project pp
                          ON pp.id = aal.project_id
                    WHERE aal.x_validated = TRUE
                      AND COALESCE(aal.x_personal_record, FALSE) = FALSE
                      AND pp.x_is_charity_parent = TRUE
                      AND pt.x_charity_category_id IS NOT NULL
                      AND NOT EXISTS (
                          SELECT 1 FROM hr_attendance ha
                          WHERE ha.x_charity_task_id = aal.task_id
                            AND ha.employee_id = aal.employee_id
                            AND ha.check_in::date = aal.date
                            AND ha.x_validated = TRUE
                      )
                ),
                line_aggs AS (
                    SELECT
                        category_id,
                        lodge_year,
                        SUM(CASE WHEN NOT is_helper THEN hours ELSE 0 END)
                            AS elks_hours,
                        SUM(CASE WHEN is_helper THEN hours ELSE 0 END)
                            AS helper_hours,
                        COUNT(DISTINCT CASE WHEN NOT is_helper
                                            THEN employee_id END)
                            AS elks_unique,
                        COUNT(DISTINCT CASE WHEN is_helper
                                            THEN employee_id END)
                            AS helper_unique,
                        COUNT(CASE WHEN NOT is_helper THEN 1 END)
                            AS elks_headcount,
                        COUNT(CASE WHEN is_helper THEN 1 END)
                            AS helper_headcount,
                        SUM(CASE WHEN NOT is_helper THEN miles ELSE 0 END)
                            AS elks_miles,
                        SUM(CASE WHEN is_helper THEN miles ELSE 0 END)
                            AS helper_miles,
                        SUM(cash_value)     AS line_cash,
                        SUM(non_cash_value) AS line_non_cash
                    FROM deduped_lines
                    GROUP BY category_id, lodge_year
                ),
                contrib_aggs AS (
                    SELECT
                        pt.x_charity_category_id  AS category_id,
                        pp.x_lodge_year           AS lodge_year,
                        SUM(c.cash_value)         AS contrib_cash,
                        SUM(c.non_cash_value)     AS contrib_non_cash,
                        SUM(c.elks_count)         AS contrib_elks,
                        SUM(c.helper_count)       AS contrib_helpers,
                        SUM(c.head_count)         AS contrib_heads,
                        SUM(COALESCE(c.elks_hours, 0))    AS contrib_elks_hours,
                        SUM(COALESCE(c.helper_hours, 0))  AS contrib_helper_hours,
                        SUM(COALESCE(c.elks_miles, 0))    AS contrib_elks_miles,
                        SUM(COALESCE(c.helper_miles, 0))  AS contrib_helper_miles
                    FROM elks_charity_contribution c
                    JOIN project_task pt    ON pt.id = c.task_id
                    JOIN project_project pp ON pp.id = pt.project_id
                    WHERE c.state = 'confirmed'
                      AND pp.x_is_charity_parent = TRUE
                      AND pt.x_charity_category_id IS NOT NULL
                    GROUP BY pt.x_charity_category_id, pp.x_lodge_year
                ),
                activity_aggs AS (
                    SELECT
                        pt.x_charity_category_id  AS category_id,
                        pp.x_lodge_year           AS lodge_year,
                        COUNT(*)                  AS activity_count
                    FROM project_task pt
                    JOIN project_project pp ON pp.id = pt.project_id
                    WHERE pp.x_is_charity_parent = TRUE
                      AND pt.x_charity_category_id IS NOT NULL
                    GROUP BY pt.x_charity_category_id, pp.x_lodge_year
                )
                SELECT
                    -- Stable synthetic ID per (category, lodge_year).
                    -- Encode the lodge year's start (YYYY) × 100000
                    -- + category_id.  Safe as long as category_id < 100000
                    -- (current data caps at code 9999 → < 1000 categories).
                    (CAST(SPLIT_PART(base.lodge_year, '-', 1) AS INTEGER)
                        * 100000 + base.category_id)  AS id,
                    base.category_id,
                    base.category_code,
                    base.category_name,
                    base.gl_section,
                    base.lodge_year,
                    COALESCE(la.elks_hours, 0)
                      + COALESCE(ca.contrib_elks_hours, 0)
                                                     AS elks_hours,
                    COALESCE(la.helper_hours, 0)
                      + COALESCE(ca.contrib_helper_hours, 0)
                                                     AS helper_hours,
                    COALESCE(la.elks_hours, 0)
                      + COALESCE(la.helper_hours, 0)
                      + COALESCE(ca.contrib_elks_hours, 0)
                      + COALESCE(ca.contrib_helper_hours, 0)
                                                     AS total_hours,
                    COALESCE(la.elks_unique, 0)      AS elks_unique,
                    COALESCE(la.helper_unique, 0)    AS helper_unique,
                    COALESCE(la.elks_headcount, 0)
                      + COALESCE(ca.contrib_elks, 0) AS elks_headcount,
                    COALESCE(la.helper_headcount, 0)
                      + COALESCE(ca.contrib_helpers, 0)
                                                     AS helper_headcount,
                    COALESCE(la.elks_miles, 0)
                      + COALESCE(ca.contrib_elks_miles, 0)
                                                     AS elks_miles,
                    COALESCE(la.helper_miles, 0)
                      + COALESCE(ca.contrib_helper_miles, 0)
                                                     AS helper_miles,
                    COALESCE(la.line_cash, 0)
                      + COALESCE(ca.contrib_cash, 0) AS cash_raised,
                    COALESCE(la.line_non_cash, 0)
                      + COALESCE(ca.contrib_non_cash, 0)
                                                     AS non_cash_raised,
                    COALESCE(aa.activity_count, 0)   AS activity_count,
                    (SELECT id FROM res_currency
                       WHERE name = 'USD' LIMIT 1)   AS currency_id
                FROM base
                LEFT JOIN line_aggs    la ON la.category_id = base.category_id
                                          AND la.lodge_year = base.lodge_year
                LEFT JOIN contrib_aggs ca ON ca.category_id = base.category_id
                                          AND ca.lodge_year = base.lodge_year
                LEFT JOIN activity_aggs aa ON aa.category_id = base.category_id
                                           AND aa.lodge_year = base.lodge_year
            )
        """.format(table=self._table)
        self.env.cr.execute(query)
